---
platform: linux

image_resource:
    type: docker-image 
    source:
        repository: node
        tag: latest

inputs:
    - name: react-app-2

params:
    HELLO:

run:
    path: react-app-2/ci/scripts/build.sh
